version: "2"

services:
  mongo:
    image: mongo
    container_name: lambert-mongo
    volumes:
      - ./data/mongodb:/data/db

  redis:
    image: redis
    container_name: lambert-redis

  node:
    build:
      context: './'
      dockerfile: 'node/Dockerfile'
    container_name: lambert-node
    volumes:
      - ./backend/:/app/backend/
    links:
      - mongo
      - redis
    ports:
      - "7001:7001"

  # nginx:
  #   build: './nginx'
  #   ports:
  #     - "80:80"
  #   container_name: lambert-nginx
  #   links:
  #     - node
