version: "2"

services:
  mongo:
    image: mongo
    container_name: lambert-mongo
    volumes:
      - ./data/mongodb:/data/db

  redis:
    image: redis
    container_name: lambert-redis

  node:
    build:
      context: './'
      dockerfile: 'node/Dockerfile'
    container_name: lambert-node
    volumes:
      - ./backend/:/app/backend/
    links:
      - mongo
      - redis
    ports:
      - "7001:7001"

  nginx:
    image: nginx
    container_name: lambert-nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    ports:
      - "9999:80"
    links:
      - node
