version: "2"

services:
  mongo:
    image: mongo
    container_name: lambert-mongo
    volumes:
      - ./data/mongodb:/data/db

  redis:
    image: redis
    container_name: lambert-redis

  backend:
    image: builder:v1
    container_name: lambert-backend
    working_dir: /app/backend/modules/demo
    volumes:
      - ./backend/:/app/backend/
    links:
      - mongo
      - redis
    ports:
      - "7001:7001"
    command: sh -c "npm install && npm run dev"

  frontend:
    image: builder:v1
    container_name: lambert-frontend
    working_dir: /app/frontend/modules/demo
    volumes:
      - ./frontend/:/app/frontend/
    ports:
      - "7002:7002"
    command: sh -c "npm install"

  web:
    image: nginx
    container_name: lambert-web
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    volumes_from:
      - frontend
    ports:
      - "80:80"
    links:
      - frontend
      - backend
