FROM node
# RUN mkdir -p /app/backend
# COPY ./backend /app/backend
# WORKDIR /app/backend/modules/demo
# RUN npm install
WORKDIR /app/backend/modules/demo
EXPOSE 7001
# CMD ["npm", "install", "&&", "npm", "start"]
CMD npm install && npm start
